base: body
left_front:
  - front_left_hip
  - front_left_upper_leg
  - front_left_lower_leg
  - front_left_foot

right_front:
  - front_right_hip
  - front_right_upper_leg
  - front_right_lower_leg
  - front_right_foot

left_hind:
  - back_left_hip
  - back_left_upper_leg
  - back_left_lower_leg
  - back_left_foot

right_hind:
  - back_right_hip
  - back_right_upper_leg
  - back_right_lower_leg
  - back_right_foot